#!/usr/bin/env bash

info () {
  printf "\r  \033[00;34m   -->\033[0m $1\n"
}

user_prompt () {
  echo ''
  printf "\r  \033[01;34m?¿ \033[00;34m-->\033[0m $1\n"
  echo ''
}

success () {
  echo ''
  printf "\r  ✨ \033[00;32m-->\033[0m $1\n"
  echo ''
}

fail () {
  echo ''
  printf "\r  🛑 \033[0;31m-->\033[0m $1\n"
  echo ''
  exit
}
