#!/usr/bin/env bash
#
# run anything called `install.sh`

set -e

DOTFILES=${1:-"$HOME/.fotdiles"}
source $DOTFILES/functions/log

run_single_installer() {
	installer=$1
	info "running ${installer}"
	sh "${installer}"
}

run_installers() {
	info 'running installers...'

	cd $DOTFILES

	# run the homebrew installer first since other stuff depends on the things it installs
	run_single_installer "./homebrew/install.sh"

	for installer in $(find . -name install.sh); do
		if [[ "$installer" != *"homebrew"* ]]; then
			run_single_installer $installer
		fi
	done
}

run_installers
success "all installers run successfully!"
