#!/bin/bash

today="$(date +%F)"
pattern="t:([0-9]+-[0-9]+-[0-9]+)"

while read LINE; do
	if [[ $LINE =~ $pattern ]]; then
		scheduled="${BASH_REMATCH[1]}"

		if [[ $scheduled > $today ]]; then
			false
		else
			echo $LINE
		fi
	else
		echo $LINE
	fi
done
