#!/usr/bin/env bash

action=$2
shift
query=${@:2}

function usage {
	echo "  $(basename $0) <action> <note>"
	echo "    Examples:"
	echo "      $ $TODO_SH notes list"
	echo "          - list all notes"
	echo "      $ $TODO_SH notes daily"
	echo "          - make new note file for the current day"
	echo "      $ $TODO_SH notes find <query>"
	echo "          - find a notes file and open it"
	echo "      $ $TODO_SH notes archive <query>"
	echo "          - move file from main notes directory to archive"
	echo "      $ $TODO_SH notes archiveold"
	echo "          - move all daily notes files other than today's to the archive"
	echo "      $ $TODO_SH notes grep <query>"
	echo "          - search all notes files for the given word or phrase"
	echo ""
	exit
}

today="$(date +%F).txt"

function archiveold {
	dailies=($NOTES_DIR/*-*-*.txt)

	for f in "${dailies[@]}"; do
		filename=$(basename "$f")
	
		if [[ ! "$filename" == "$today" ]]; then
			mv "$NOTES_DIR/$filename" "$NOTES_DIR/archive/$filename"
			echo "$filename archived"
		fi
	done

	echo "all expired daily notes archived"
}

function archive {
	if [[ "$query" == "old" ]]; then
		archiveold
		exit
	fi

	cd $NOTES_DIR

	filename=$(fzf +i -q "$query")
	mv $filename archive/$filename
	echo "$filename archived"
}

function daily {
	filename="$NOTES_DIR/$today"

	if [[ ! -f $filename ]]; then
		touch $filename
	fi

	echo "Daily notes file created at $today"

	open $filename
}

function find {
	cd $NOTES_DIR

	if [[ "$query" == "today" ]]; then
		query="$today"
	elif [[ "$query" == "yesterday" ]]; then
		query="$(date -v -1d +%F)"
	fi

	open $(fzf +i --preview='head -20 {+}' --preview-window=right:wrap -q "$query")
}

function list {
	ls $NOTES_DIR
}

function grep {
	rg -il "$query" $NOTES_DIR | fzf +i --preview='head -20 {+}' --preview-window=right:wrap --bind "enter:execute(open {})" --bind "q:accept"
}


[[ -z "$action" ]] || [[ "$action" == "usage" ]] && usage

if [[ -z "$NOTES_DIR" ]]; then
	echo "Notes directory not set!"
	echo "Please set NOTES_DIR in .todo.cfg"
	echo ""
	exit
fi

$action $query
